### ISSUE TITLE
default.latex: Package fixltx2e Warning: fixltx2e is not required with releases after 2015(fixltx2e)

### ISSUE THREAD

**Issue by geniusupgrader** [jgm/pandoc-templates#1]
proposal to remove the line: `\usepackage{fixltx2e} % provides \textsubscript` some day.

Maybe see this: [how to use fixltx2e only when necessary](https://tex.stackexchange.com/questions/287146/how-to-use-fixltx2e-only-when-necessary)

**Comment by jgm** [comment]
As noted in README, issues should go to jgm/pandoc, not here.
