### ISSUE TITLE
LaTeX figures appear before text in pandoc markdown

### ISSUE THREAD

**Issue by scls19fr** [jgm/pandoc-templates#105]
Hello,

I'm facing same issue as http://tex.stackexchange.com/questions/101725/latex-figures-appear-before-text-in-pandoc-markdown

I added (before abstract) in my `metadata.yaml` 

    header-includes:
        - \usepackage{float}

but it doesn't seems to fix anything.

Maybe template should be improve to fix this floating "issue" more easily for LaTeX beginners.

Kind regards

**Comment by jgm** [comment]
Try adding

    \usepackage{float}
    \floatplacement{figure}{H}

in your template.

**Comment by scls19fr** [comment]
It din't worked as expected.

It works fine with

    \let\origfigure=\figure
    \let\endorigfigure=\endfigure
    \renewenvironment{figure}[1][]{%
      \origfigure[H]
    }{%
      \endorigfigure
    }

**Comment by jgm** [comment]
I don't want to change the template here, for a couple reasons.  First, I want to avoid depending on the `float` package, and second, disabling floating figures is not always what is wanted.  For optimal layout, you sometimes need figures to float to a point before they're referred to.
