### ISSUE TITLE
Section numbering depth

### ISSUE THREAD

**Issue by azrdev** [jgm/pandoc-templates#111]
Currently default.latex contains:

```
$if(numbersections)$
\setcounter{secnumdepth}{5}
$else$
\setcounter{secnumdepth}{0}
$endif$
```

Is it possible to make $numbersections an integer instead of a boolean, and pass the argument directly through? Maybe with a fallback to provide backwards-compatibility with boolean values

**Comment by wilx** [comment]
I believe this can be closed as this is already implemented by https://github.com/jgm/pandoc-templates/commit/856a5093269cc8e5aaa429fc1775157ff5857c30.

**Comment by jgm** [comment]
Thanks
