### ISSUE TITLE
Consider adding font encoding variable to LaTeX template

### ISSUE THREAD

**Issue by dluciv** [jgm/pandoc-templates#112]
Please consider adding font encoding variable to LaTeX template. Many languages require other encodings than T1.

**Comment by adunning** [comment]
Can you give an example of how you would want the variable to appear?

**Comment by dluciv** [comment]
Sure. For the case of https://github.com/jgm/pandoc-templates/blob/master/default.latex it can look as follows (or something like it):

```
\usepackage[$if(fontenc)$$fontenc$$else$T1$endif$]{fontenc}
```

**Comment by adunning** [comment]
Thanks! I'll include that in another pull request I'm preparing to realign the LaTeX and beamer templates, unless you want to submit it.

I assume that `\usepackage[utf8]{inputenc}` can be left as-is when using something else for `fontenc`?

**Comment by dluciv** [comment]
About inputenc, there Pandoc itself prints out UTF8, so `\usepackage[utf8]{inputenc}` should be enough.

There is also `utf8x` input encoding, but it is [not recommended](http://tex.stackexchange.com/questions/13067/utf8x-vs-utf8-inputenc) anyway.
