### ISSUE TITLE
2 suggestions about the man page template

### ISSUE THREAD

**Issue by alexvong1995** [jgm/pandoc-templates#117]
Hi everyone,

I am a new user of pandoc. Thanks for making pandoc available under the GPL! I used [pod2man](http://perldoc.perl.org/pod2man.html) previously to generate man page. Now the project I am interested in wrote their documentation in Markdown. I noticed there are some good features that is in pod2man but not in pandoc:

1. pod2man-generated man page has ```.\" Automatically generated by Pod::Man 2.28 (Pod::Simple 3.28)                 ``` in the beginning of the generated file. IMHO, this makes it clear that it is a generated file.

2. pod2man-generated man page has
```
.\" For nroff, turn off justification.  Always turn off hyphenation; it makes   
.\" way too many mistakes in technical documents.                               
.if n .ad l
.nh
```
right after the `.TH` macro. I think it is a great idea to turn off justification and hyphenation because of the reason mentioned in the comment.

Please tell me how do you think about these suggestions. I think 2. is easy to implement but I don't know how to extract the version string of pandoc so that 1. works. Any suggestions are welcomed!

**Comment by jgm** [comment]
I think (1) is a good idea.  Getting the version number in
there would require setting a template variable in the
man page writer, but we could do this easily enough.

(2) is more opinionated.  On my systems, most man pages seem
to use both hyphenation and justification when viewed on the
terminal.  We could perhaps add `justify` and `hyphenate`
variables, which you could set in the metadata, and which
would trigger this code.

+++ alexvong1995 [Sep 16 15 08:21 ]:
>   Hi everyone,
>
>   I am a new user of pandoc. Thanks for making pandoc available under the
>   GPL! I used [1]pod2man previously to generate man page. Now the project
>   I am interested in wrote their documentation in Markdown. I noticed
>   there are some good features that is in pod2man but not in pandoc:
>    1. pod2man-generated man page has .\" Automatically generated by
>       Pod::Man 2.28 (Pod::Simple 3.28) in the beginning of the generated
>       file. IMHO, this makes it clear that it is a generated file.
>    2. pod2man-generated man page has
>
>.\" For nroff, turn off justification.  Always turn off hyphenation; it makes
>.\" way too many mistakes in technical documents.
>.if n .ad l
>.nh
>
>   right after the .TH macro. I think it is a great idea to turn off
>   justification and hyphenation because of the reason mentioned in the
>   comment.

>   Please tell me how do you think about these suggestions. I think 2. is
>   easy to implement but I don't know how to extract the version string of
>   pandoc so that 1. works. Any suggestions are welcomed!

**Comment by alexvong1995** [comment]
Okay, I will try to read more about template variable then. Your reply is quick!
