### ISSUE TITLE
contentsname in default.latex

### ISSUE THREAD

**Issue by MAccadia** [jgm/pandoc-templates#125]
I suggest to add the possibility to change the name of the table of contents since it's critical for non-english users. 

default.latex
```
$if(toc)$
{
\hypersetup{linkcolor=black}
\setcounter{tocdepth}{$toc-depth$}
\renewcommand\contentsname{$contents-name$}
\tableofcontents
}
$endif$
```

Thanks for making pandoc.

**Comment by jgm** [comment]
This should be done automatically if you localize using
babel or polyglossia, no?

+++ MAccadia [Oct 04 15 10:18 ]:

**Comment by MAccadia** [comment]
Oops, I didn't know this option. It works. Thanks.
