### ISSUE TITLE
Biblatex options

### ISSUE THREAD

**Issue by twsh** [jgm/pandoc-templates#147]
There’s an option to set styles for natbib. Would it make sense to have a variable for setting biblatex options? I can add something and make a pull request if it’s a good idea.

**Comment by jgm** [comment]
It would be good to use the existing variable biblio-style if possible.

+++ Thomas Hodgson [Nov 13 15 17:12 ]:

**Comment by twsh** [comment]
I see what you mean. I don't see why that wouldn't be possible. And the template could include the 'style=' then.

Here's why I didn't originally suggest that: I't's possible to set other sorts of options as well, not just a bibliography style. And one might want to set the citation and bibliography styles independently which requires two options and would require not having 'style=' in the template.

**Comment by jgm** [comment]
If you put together a PR I'll comment on it.

+++ Thomas Hodgson [Nov 16 15 09:54 ]:

**Comment by twsh** [comment]
I've done that here using 'biblatex-options': https://github.com/jgm/pandoc-templates/pull/152

I can change it if you think that's best.

Biblio-style currently expects just one thing; I was thinking of this as more like the options to pass to fontspec.sty.

**Comment by jgm** [comment]
Closed by your PR.
