### ISSUE TITLE
LaTeX keywords

### ISSUE THREAD

**Issue by twsh** [jgm/pandoc-templates#153]
Now that the LaTeX template supports keywords, would it be a good idea to include them in the document? Something like:

```
$if(keywords)$
$for(keywords)$$keywords$$sep$; $endfor$
$endif$
```

This could come after the abstract. It would be good to think about how to format it. Perhaps it should be in a block of its own rather than just an ordinary paragraph e.g. in a `\begin{center}...\end{center}`? I thought about adding 'Keywords', but that only makes sense for documents written in English.

**Comment by adunning** [comment]
I added it only because it's a standard metadata element shared between many of the formats supported by Pandoc. But it's an interesting question as to whether the typical user would also expect these to be printed somewhere; one does sometimes see this in journal articles.

**Comment by twsh** [comment]
I’m thinking about journal articles too, and especially manuscripts for submission to journals which do ask for this sometimes. If I’m making a PDF, then, if I bother to set keywords it would be because I want to see them printed. I don’t know if that’s typical.

**Comment by blindmelon** [comment]
Personally I am most likely to want the keywords in the PDF metadata and *not* visible on a printed page, but I don't create them to submit to journals.

**Comment by twsh** [comment]
One thing that occurred to me is that it would be possible to define a command like this if there are keywords:

```
\newcommand{\keywords}{%
$for(keywords)$$keywords$$sep$; $endfor$}
```

The user can then put `\keywords` wherever they like to print them if they want to. That makes them optional without cluttering things with another option.

**Comment by jgm** [comment]
Some journals print the keywords after the abstract, or in
another place.  Others don't print keywords; they only
include them in the metadata.  I'm not sure which is more
common, but I'm inclined not to make printing the keywords
the default.

+++ Thomas Hodgson [Nov 18 15 01:03 ]:
