### ISSUE TITLE
Loading lmodern.sty in LaTeX and Beamer templates 

### ISSUE THREAD

**Issue by twsh** [jgm/pandoc-templates#165]
I ran into a problem using a beamer theme which loads fonts. The Beamer template loads lmodern.sty (when there's no font family option) and this overrides what the theme did.

The quickest fix would be to remove the call to lmodern.sty. This means that pdftex output will be Computer Modern, which looks the same, and xelatex will be Latin Modern. Is there a reason I don't know about for not doing this? If not, I'll make a PR.

This is probably only a problem for Beamer, but if modern.sty isn't needed there then perhaps it shouldn't be in the LaTeX template either.

**Comment by jgm** [comment]
The reason for using lmodern, if I recall, was to get
support for more non-ASCII characters.  But it is a problem
if this overrides the theme.  Would it work to put the
font stuff in front of the theme stuff in the template?


+++ Thomas Hodgson [Dec 08 15 06:33 ]:

**Comment by twsh** [comment]
That seems to work when I test it.

**Comment by jgm** [comment]
Want to make a PR?  We could then ask others to comment.

+++ Thomas Hodgson [Dec 08 15 09:48 ]:

**Comment by twsh** [comment]
I'll do that.

**Comment by jgm** [comment]
Closed by your PR.
