### ISSUE TITLE
\urlstyle{same} in Beamer and LaTeX

### ISSUE THREAD

**Issue by twsh** [jgm/pandoc-templates#166]
The LaTeX template sets `\urlstyle{same}`, the Beamer one doesn't. I can think of reasons for either choice, but I think that the templates should both do the same thing.

Personally, I would set it for both: if links should be visually distinguished it's easy enough to do it with colour.

**Comment by jgm** [comment]
Why closed?  I've intended to look into this, but just
haven't gotten around to it.

+++ Thomas Hodgson [Jan 11 16 03:48 ]:

**Comment by twsh** [comment]
A worry occurred to me: the template doesn't load hyperref.sty. So, if the template has `\urlstyle{same}` and is used with another class it will break. Although other things in the template would break too, and arguably nobody should expect the Beamer template to work with another class.

**Comment by jgm** [comment]
+++ Thomas Hodgson [Jan 11 16 12:01 ]:
>   A worry occurred to me: the template doesn't load hyperref.sty. So, if

Probably because beamer itself does.  It would be worth
checking on that, but generally we need hyperref, so if
it's not in the beamer template, it's probably because
beamer loads it by default.

**Comment by jgm** [comment]
Oh, yes -- there's no reason we should have a configurable
documentclass in the beamer template.  The variable should
just be replaced by 'beamer'.

+++ Thomas Hodgson [Jan 11 16 12:01 ]:

**Comment by twsh** [comment]
I checked the manual to be sure. Beamer does load hyperref.
