### ISSUE TITLE
Location of header-includes in LaTeX and Beamer templates

### ISSUE THREAD

**Issue by twsh** [jgm/pandoc-templates#168]
In the Beamer template the header-includes come after the `\title` etc. In the LaTeX template they come before them. Wouldn't it make sense for them to be the same?

I like being able to load titling.sty with an include and have it pick up the title, author, and date which it can only do if it comes before them. And it seems like it makes sense to set these things after everything else in the preamble.

**Comment by jgm** [comment]
Makes sense to me.  Can anyone think of a reason why this
should not be changed?

+++ Thomas Hodgson [Dec 09 15 05:27 ]:

**Comment by twsh** [comment]
I will make a PR.

**Comment by jgm** [comment]
Closed by your PR.
