### ISSUE TITLE
Beamer figure captions

### ISSUE THREAD

**Issue by twsh** [jgm/pandoc-templates#171]
When I was looking at the Beamer template I saw these lines:
```
\setbeamertemplate{caption}[numbered]
\setbeamertemplate{caption label separator}{: }
\setbeamercolor{caption name}{fg=normal text.fg}
```
Am I right in thinking that these are purely cosmetic changes? If so, shouldn't they be the sort of thing that's controlled by a theme and not set in the template?

**Comment by jgm** [comment]
This was introduced by commit 6db8eff46ab97a133ed2b17e21455de8b9d4447d.
I'm not sure what the intent was since there's no linked issue.
@aaronwolen can you comment?

**Comment by twsh** [comment]
I think I found the intent here: https://github.com/jgm/pandoc-templates/pull/44

It was to make the figure captions match table captions.
