### ISSUE TITLE
Pass biblatexoptions when loading biblatex

### ISSUE THREAD

**Issue by anntzer** [jgm/pandoc-templates#201]
Currently, biblatexoptions are passed separately:
```
$if(biblatex)$
\usepackage$if(biblio-style)$[style=$biblio-style$]$endif${biblatex}
$if(biblatexoptions)$\ExecuteBibliographyOptions{$for(biblatexoptions)$$biblatexoptions$$sep$,$endfor$}$endif$
```
This prevents the setting of load-time options, most importantly the backend.  Would there be any disadvantage to pass the options directly when calling `\usepackage{biblatex}`?

**Comment by jgm** [comment]
These were added in #152.
Pinging @twsh to comment on your suggestion...

+++ Antony Lee [Jun 16 16 12:32 ]:

**Comment by twsh** [comment]
I think that would be fine. As far as I know, any option can be given as a package option. I can't now recall why I went for the way of doing it that I did. The suggestion would be an improvement.

@anntzer Would you like to make a PR? If not, I will.

**Comment by anntzer** [comment]
Can you take care of it? Thanks.

**Comment by twsh** [comment]
I remember what my reason was now. If there are both biblio-style and biblatexoptions in their I wasn't sure where to put the brackets and commas. So I went for my solution. I will think about how to do it.
