### ISSUE TITLE
Options for LaTeX beamer theme

### ISSUE THREAD

**Issue by steko** [jgm/pandoc-templates#206]
Hi, following up on #190 and https://github.com/matze/mtheme/issues/201 and since I'm using the Metropolis theme as well, I was wondering if there is a way to pass theme options, like _titleformat_, via Pandoc without resorting to a customized template.

Thanks

**Comment by twsh** [comment]
This could be added easily enough, if it's worth adding more options.
`\usetheme[$for(themeoptions)$$themeoptions$$sep$,$endfor$]{$theme$}\`

**Comment by cagix** [comment]
Since the proposed solution is really useful for other beamer themes too: Is there any chance to get this into the default template?
