### ISSUE TITLE
`header-includes` cannot be used as template fragments

### ISSUE THREAD

**Issue by ickc** [jgm/pandoc-templates#220]
1. I found that if I wrote a template fragment and include it by `-H/--include-in-header=`, the `$...$` will be left as is and not processed.

2. I also found that although pandoc would look for the `--template=<FILE>` from the user data directory first (*e.g.* `~/.pandoc/template/`), but if `-H <FILE>` is used, pandoc won't look for it from the user data directory.

I tried to search for issue related to these, but there aren't any. So it doesn't seem for the others to think it is an issue. But at least it seems it won't be harmful if the said 2 behaviors are implemented.

The use for the above behavior is to have fragments of custom templates. Rather than managing 1 modified, complete template from the official one, I can put my custom code in separate files. This approach has the advantages of:

1. Do not need to manually make pull request from the official template to the custom ones. If the default template is left untouched, the template "version" will sync with the pandoc version when it is updated. This would be more painful if one has more than 1 custom templates for the same format.

2. more modular: all the benefits of "static" include (that don't process the `$...$`) will benefits custom template writing as well.

3. custom templates usually (or is it true?) are slightly modified from the official one. *e.g.* the LaTeX output expects a lot of packages and it would be very difficult to write a totally new template from the ground up. If all we do is to take the default template and add a few lines, which often the time do not interact with the original code, than using `include` is easier to write those templates.

An example of include-template is in [ickc/pandoc-templates at include-in-header](https://github.com/ickc/pandoc-templates/tree/include-in-header).

To make an analogy, in Jekyll, there's liquid templating. The "liquid" will be processed whether or not it is in `includes` or `layouts` (or even the "main document" but that shouldn't apply here).

To conclude, the proposal is

1. If a file is included (say by `-H/--include-in-header=`), it would be included in the template *before* it is being processed (those `$...$`).

2. Whenever include is used, it will also search for it in `data-dir`. We could use the same folder as the template does: `templates`. Or if we want to keep it separate, perhaps a folder `includes`.

And to make it clear, although I mentioned `include-in-header`, `--include-before/after-body=` should be treated equally.

**Comment by cagix** [comment]
I remember some earlier discussion on this topic. The workaround was to run pandoc twice, first on the custom template fragment to process things and then including the processed template fragment using `-H` in the second run ... Like in 

```
pandoc  --template=template_snippet  document.md  -o processed_snippet
pandoc  -H processed_snippet  document.md  -o document.pdf
```

But it would make things much easier, if pandoc would include the `-H` files before processing the `$...$`. 

+1

**Comment by ickc** [comment]
> The workaround was to run pandoc twice, first on the custom template fragment to process things and then including the processed template fragment using -H in the second run ...

Excellent! I tested it and it worked! But I don't understand the syntax in the first line. I don't see why the content of the `document.md` won't appears in `processded_snippet`. Can @cagix enlighten me?

And do you recall why it hasn't been "fixed"? Does it mean this won't considered to be changed?

Although the trick works, I am afraid about the performance issue. I am now working on a project that involves dozens of small `md` files and the initial build is already quite long. By the end of the project, I think there would be ~1000 small `md` files so I want to squeeze more performance from that.

> But it would make things much easier, if pandoc would include the -H files before processing the $...$.

Totally agree!

**Comment by cagix** [comment]
> I don't see why the content of the document.md won't appears in processded_snippet.

In the first line the snippet acts just as a template, i.e. all `$...$` will be processed. 

The only reason to specify also the `document.md` is to extract the meta data from the document, i.e. from the yaml header ... May be you can omitt it when you specify all (needed) variables using command line options (not tested).

The contents of `document.md` should appear in the processed snippet, if you include `$body$` in your snippet (not tested).

**Comment by cagix** [comment]
> And do you recall why it hasn't been "fixed"? Does it mean this won't considered to be changed?

I think there were reasons for this, but I can't remember. And the search function can't find the issue, either ... *grml*

**Comment by ickc** [comment]
>The contents of document.md should appear in the processed snippet, if you include $body$ in your snippet (not tested).

Ah... it makes sense. Didn't study the template enough to notice the use of `$body$`. Thanks!

Regarding the reasoning, I guess, especially with LaTeX's freq. use of `$`, may be they think it will confuse the user if they were treated as template language, not LaTeX.

I think if there's a reason why the current behavior is preferred, we'd better document the reason and the trick to work around it. I'm pretty sure the said trick wasn't in the manual.

**Comment by ickc** [comment]
@cagix, thanks again for your mentioning of the trick:

> pandoc  --template=template_snippet  document.md  -o processed_snippet
> pandoc  -H processed_snippet  document.md  -o document.pdf

I tried to optimized it for performance, and come up with something like this

```bash
MD=$(<document.md)
echo "$MD" | pandoc --include-in-header=<(echo "$MD" | pandoc --template=template_snippet) -o "document.html"
```

The idea is that I only need to read `document.md` once, and do not need to write the intermediate file (which is more secure too). Can it be improved further? (I'm thinking may be I should trim out onlt the yaml front matter for the first run too. Don't know how much pandoc is doing if the template don't call the body)

#### Digression about performance:

I tried to time it and see how the 2 compares, and also want to know how much extra overhead it (calling pandoc twice) introduce. I used a test file, and the (real) time are:

| complete template	| template snippet	| template snippet "optimized"	|  
|  ------	| ------	| ------	|  
| 0.333s	| 0.477s	| 0.467s	| 

Sadly the optimization seems negligible, but the need to run pandoc twice greatly reduces the speed.

**Comment by ickc** [comment]
I just realized I made a mistake. This is not an issue about `pandoc-templates` but `pandoc` itself. I am closing this one. Sorry!

**Comment by ickc** [comment]
@cagix, I put your trick into <https://github.com/jgm/pandoc/wiki/Pandoc-Tricks>. I think there should be a central place to document it. Thanks again!
