### ISSUE TITLE
Page break before and after Table of Contents in default.latex

### ISSUE THREAD

**Issue by fnadde42** [jgm/pandoc-templates#221]
The feature pandoc offers with the flag `--toc` is really neat but when my documents (usually protocols after organisations annual meetings) become larger than just a few pages and a TOC becomes necessary, it also seems natural to have a title page followed by a _new page_ for the TOC followed by a _new page_ for the content. To me this seems natural and I think this is normal when using a TOC in almost any case. It is possible to edit this oneself but the example above should be the normal behaviour in my opinion.

**Comment by jgm** [comment]
Note that you can achieve this using a custom template.
Then you don't have to edit the resulting files manually.

+++ Petter Karkea [Oct 14 16 00:58 ]:

**Comment by fnadde42** [comment]
Ok. So I'm trying to convert Markdown to PDF (via LaTeX). So I tried this but it did not work (I obviously messed something up).

1. Copy the default template `default.latex` from `/usr/share/pandoc/data/templates` to directory `/tmp` (for test)
2. Modified the original `default.latex` -> `modified.latex` like this (I'm very new to LaTeX):
    
    `default.latex`
    ```latex
    $if(toc)$
{
\hypersetup{linkcolor=black}
\setcounter{tocdepth}{$toc-depth$}
\tableofcontents
}
$endif$
$body$
    ```
    
    `modified.latex`
    ```latex
    $if(toc)$
{
\newpage
\hypersetup{linkcolor=black}
\setcounter{tocdepth}{$toc-depth$}
\tableofcontents
\newpage
}
$endif$
$body$
    ```
3. Ran this command: `pandoc -f markdown --template="/tmp/modified.latex" --toc input.md -o output.pdf`
4. Get this error:
    ```text
    ! Undefined control sequence.
l.91 \tightlist

pandoc: Error producing PDF
    ```
5. Suspects my modifications have something to do with it so copies the `default.latex` to the `/tmp`-directory and runs the same command but with `--template="/tmp/default.latex"`
6. Same error but this time it's two rows before (even though I only edited rows after) 
    ```text
    ! Undefined control sequence.
l.89 \tightlist

pandoc: Error producing PDF
    ```
   The problem seems to originate from this block:
   ```latex
   87: \ifxetex
88:   \usepackage[setpagesize=false, % page size defined by xetex
89:               unicode=false, % unicode breaks when used with xetex
90:               xetex]{hyperref}
91: \else
92:   \usepackage[unicode=true]{hyperref}
93: \fi
   ```

Needless to say, I'm a bit confused here...

**Comment by jgm** [comment]
You're using an older version of the default template,
apparently.  Try generating a fresh copy of the default
template using pandoc itself:

    pandoc -D latex > default.latex

Check, it should contain a declaration for `\tightlist`.
Modify that version and proceed as before.

**Comment by fnadde42** [comment]
Thanks! It works now.

As I suggested earlier, this behaviour I modified my default template to produce should in my view be the default template. The left part in the image is the current default when using a table of contents and the right one is what I think should happen when a user renders a PDF with the `--toc`-flag.

When I have a small document I really do not need a TOC so in that case I would want the content to start on the same page right under my title. However, when I have exceeded about 7 to 10 pages I would want the readers to find it more easily and therefore insert a TOC. I have written and read a lot of reports but none where the TOC is on the frontpage and where the content start right after the last item on the TOC. Documents containing a TOC usually looks like the right part of the image below and that is what I think should be the default behaviour.

Please enlighten me if I am missing something.

![toc-page2](https://cloud.githubusercontent.com/assets/1107419/19408508/6713fbae-92bf-11e6-8b7a-28c4d0f4243f.jpg)

**Comment by jgm** [comment]
Normally this kind of thing (whether there's a page break
before/after the TOC) is controlled by the documentclass.
Pandoc tries to generate fairly plain LaTeX, so we don't
want to build in too many assumptions about how things
should look.

Try using the report documentclass instead of article.
I believe that forces the toc to be on its own page.
Add the option

    -V documentclass=report

to your pandoc command.
See the last comment here
http://tex.stackexchange.com/questions/17883/how-to-make-toc-be-on-its-own-pages

+++ Petter Karkea [Oct 15 16 01:17 ]:

**Comment by fnadde42** [comment]
Using `-V documentclass=report` gave the TOC it's own page but gave also every level 1 heading it's own page (and the prefix "chapter") which looks weird in a meeting protocol where one heading can have only one sentence in it.

> Pandoc tries to generate fairly plain LaTeX, so we don't want to build in too many assumptions about how things should look.

I respect the philosophy of simplicity behind Pandoc and actually think it's a great idea now that I got it explained.

The best solution for me is to use a custom theme.
