### ISSUE TITLE
Problem with longtable when the latex template uses a two column layout

### ISSUE THREAD

**Issue by jpmarindiaz** [jgm/pandoc-templates#24]
When I modify the default late template to work with a two column layout
\documentclass[12pt,twocolumn,landscape]{scrartcl} 

I get the following error:
! Package longtable Error: longtable not in 1-column mode.

So longtable doesn't work with multi columns. Any ideas for a workaround?

**Comment by rriemann** [comment]
Duplicate of https://github.com/jgm/pandoc/issues/1023 . I suggest to close this issue.
