### ISSUE TITLE
Html format names. "html4", "html5", "html" etc.

### ISSUE THREAD

**Issue by JohnLukeBentley** [jgm/pandoc-templates#240]
@jgm quoting JohnLukeBentley in [default.html5. Polyglot Markup. #237](https://github.com/jgm/pandoc-templates/issues/237#issuecomment-275120456)
>> On the separate issue of format names, if I was present at the point of coining them I'd suggest:
>>
>> * Using "html4" for the  (X)HTML4 (XHTML 1.0 transitional) template;
>> * Using "html5" for (X)HTML5 (Now Polyglot Markup); and
>> * Using "html" as an alias for the latest template, in this case as an alias for "html5".
>>
>> Then
>> * Using "html6" for a new template, when and if that HTML version comes out, and then changing the "html" alias to "html6"; ... and so on.

jpm wrote
> Yes, this makes sense. I think it's probably wise to shift 'html' from html4 to html5, perhaps in the pandoc 2.0 release.

**Comment by jgm** [comment]
We're doing this now in pandoc dev.
