### ISSUE TITLE
proposal for new ConTeXt template

### ISSUE THREAD

**Issue by ousia** [jgm/pandoc-templates#246]
@adunning and @jgm,

since the last revision of `default.context`, I think it is safe to drop the `simplefonts` package, which is outdated.

I will do it myself, but I have one question.

Do you want links with borders? (Border color is only one for all kind links, and default is gray.)

``` tex
\setupinteraction[state=start, color=]
\enabledirectives[references.border]
\starttext
\startTEXpage[offset=1em]
\useURL[url1][http://pandoc.org]\from[url1]
\stopTEXpage
\stoptext
```

I don’t use the template myself, so it is up to you which color you prefer.

**Comment by ousia** [comment]
I’m making the changes and I selected _Latin Modern Roman_ (a version of _Computer Modern Roman_) as default roman typeface.

Do you prefer another one as default?

**Comment by jgm** [comment]
+++ Pablo Rodríguez [Feb 18 17 10:08 ]:
>   [1]@adunning and [2]@jgm,
>
>   since the last revision of default.context, I think it is safe to drop
>   the simplefonts package, which is outdated.
>
>   I will do it myself, but I have one question.
>
>   Do you want links with borders? (Border color is only one for all kind
>   links, and default is gray.)

I'd say no, we don't have borders by default for latex output.
It would be good to be as similar as possible to what we do
for latex.

**Comment by jgm** [comment]
+++ Pablo Rodríguez [Feb 18 17 10:22 ]:
>   I’m making the changes and I selected Latin Modern Roman (a version of
>   Computer Modern Roman) as default roman typeface.
>
>   Do you prefer another one as default?

I believe we use that for latex as the default.

**Comment by ousia** [comment]
> I'd say no, we don't have borders by default for latex output. 
It would be good to be as similar as possible to what we do
for latex.

I don’t use LaTeX myself (I don’t have it installed), but if the default for links in ConTeXt is no color and no style, adding no borders to it would make it impossible to see where a link is in some texts.

``` markdown
---
papersize: A7, landscape
---

This is an autolink: <https://pandoc.org>.

This is a standard link: [Try `pandoc` on its site](http://pandoc.org/try/).
```

See the result:

![book-1](https://cloud.githubusercontent.com/assets/203767/23104054/8c2e3bfa-f6c6-11e6-8445-dfbc8975d1e7.png)

How would you tell that the second one is a link, if it hadn’t a border?

> > I’m making the changes and I selected Latin Modern Roman (a version of
> > Computer Modern Roman) as default roman typeface.
> >
> > Do you prefer another one as default?
>
> I believe we use that for latex as the default.

Well, I asked for that because of typeface matching.

The template defines a typeface fallback for Greek glyphs with DejaVu Serif. I’d rather use _FreeSerif_ for all glyphs in non CJK languages (no fallback needed). _FreeSerif_ has many glyphs for most scripts (outside the CJK languages).

The issue here, which might differ from LaTeX, is that you cannot have a typeface fallback unless you define a font family (and you use it with `\setupbodyfont`). It won’t work.

I think the _FreeSerif_ typeface is included with _TeX Live_. But I don’t use _TeX Live_ now.

**Comment by jgm** [comment]
Just check out the current default.latex template to see
how link colorization works.

If the variable linkcolor is set, then links are colored,
otherwise not.  And they are never given borders.
Note that on a PDF you can still tell if something is
a link, even if it's not colored, by hovering the mouse
over it.

**Comment by ousia** [comment]
Fine. The new proposal has optional `linkcolor` (in ConTeXt you have only one color for all links) and _Latin Modern_ typefaces.

Closing the issue myself.
