### ISSUE TITLE
default.ms: Ineffective .ND; suggestion: (ab)use .AU

### ISSUE THREAD

**Issue by teoric** [jgm/pandoc-templates#5]
`default.ms` contains a call to `.ND`. According to `groff_ms(7)`, this is to “[p]rint the current date, or the arguments to the macro if  any, on the title page (if specified) but not in the footers.” As the default template does not produce a title page, nothing is produced for `.ND`.

Personally, I find that (ab)using the following `.AU` command after the loop produces an acceptable date.
```roff
.AU
.sp 0.5
.ft R
$date$
```

**Comment by jgm** [comment]
As noted in README, issues should go to jgm/pandoc, not here.
