### ISSUE TITLE
Add a shower template

### ISSUE THREAD

**Issue by arthurlogilab** [jgm/pandoc-templates#56]
http://shwr.me/ is an HTML/CSS/JS presentation toolkit very similar to reveljs (kudos for that)

One of its "killer" features for me is the ability to print the presentation to PDF (with the same style as the HTML presentation), this is great if you want to present in your browser then easily publish the presentation on all the platforms that don't support html presentations.

**Comment by benswift** [comment]
Hi folks, this is a very late bump to this thread, but is there any support for this - or is it a WONTFIX?

**Comment by jgm** [comment]
Could shower be supported with the existing revealjs writer + a special template?  Or would it require changes in the writer as well.  If the latter, the issue should be on pandoc, not here.  If the former, then the thing to do is to test it out with your own custom template; if you get something that works, we might consider including it.

**Comment by benswift** [comment]
I think it'll require (small) changes in the writer (i.e. the shower writer will be very similar to the revealjs one, but some of the classes added to the `<section>`s will be different).

If I can hack something together which works then I'll submit a pull request on the main pandoc repo. You can close this issue.

**Comment by jgm** [comment]
Sounds good.
