### ISSUE TITLE
default.html5: body of document should be wrapped

### ISSUE THREAD

**Issue by gfelbing** [jgm/pandoc-templates#83]
Using the default.html5, the body of the document should be wrapped into an own tag, i.e. an `<section>`-tag in order to be able to style it properly:

```
…(line 58)
$if(body)$
<section>
$body$
</section>
$endif$
…
```

**Comment by jgm** [comment]
I don't think this is correct.  Section is not a generic container element:
http://html5doctor.com/the-section-element/
And you've got a container you can style anyway -- `<body>`.
