### ISSUE TITLE
Default templates not changing

### ISSUE THREAD

**Issue by mendelkranz** [jgm/pandoc-templates#88]
Having a slight problem perhaps someone can help me with: I altered the default.latex template in the ~/.pandoc/defaults folder however the changes aren't registering when I output a pdf. When I ran '$ pandoc -D latex' it printed a different file than the one I had edited. 
Why is it not reading the default file I edited? and which file is it actually reading?

**Comment by jgm** [comment]
You need to put the template in `~/.pandoc/templates`, not
`~/.pandoc/defaults`.

+++ Mendel Kranz [Mar 26 15 01:46 ]:
