### ISSUE TITLE
reveal.js

### ISSUE THREAD

**Issue by pizzooid** [jgm/pandoc-templates#93]
To whom it may concern!

Line 93:

        center: $if(center)$$center$$else$true$endif$,                       // Vertical centering of slides

if center is set to false this line evaluates to true.

All the best
P

**Comment by jgm** [comment]
I've added a line comment on the relevant commit.

I assume the intent was to make centering the default, even when center isn't given a value. Unfortunately the template language can't distinguish between the case where center isn't given a value, and when it is given the value false. So, what to do here?  Probably we need to modify the HTML writer to set the `center` variable to `true` if it does not have a value.  We can then change the else clause to `false` in this line.
